# Generated by Django 2.1 on 2019-01-30 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erd_id', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('product_priority', models.CharField(max_length=20, null=True)),
                ('author', models.CharField(max_length=20, null=True)),
                ('version', models.CharField(max_length=10)),
                ('HLD', models.TextField(null=True)),
                ('l1_jira', models.CharField(max_length=20, null=True)),
                ('l2_jira', models.CharField(max_length=20, null=True)),
                ('bug_jiras', models.TextField(null=True)),
                ('status', models.CharField(max_length=10, null=True)),
                ('workload', models.CharField(max_length=30, null=True)),
                ('milestone', models.CharField(max_length=40, null=True)),
                ('component', models.CharField(max_length=30, null=True)),
                ('project', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=30)),
                ('snap', models.BinaryField()),
                ('tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('fw_version', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('test_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50)),
                ('case_age', models.CharField(max_length=20)),
                ('F_report_path', models.TextField(null=True)),
                ('erd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcisDB.Erds')),
            ],
        ),
        migrations.CreateModel(
            name='TestReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.CharField(max_length=10)),
                ('test_log', models.TextField()),
                ('test_date', models.CharField(max_length=20)),
                ('IR_report_path', models.TextField()),
                ('fw_version', models.CharField(max_length=50)),
                ('note', models.TextField(null=True)),
                ('description', models.CharField(max_length=100)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcisDB.TestCases')),
            ],
        ),
    ]
