# Generated by Django 2.1 on 2019-01-07 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erd_id', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('product_priority', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=10)),
                ('HLD', models.TextField()),
                ('l1_jira', models.CharField(max_length=20)),
                ('l2_jira', models.CharField(max_length=20)),
                ('bug_jiras', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('workload', models.CharField(max_length=30)),
                ('milestone', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50)),
                ('case_age', models.CharField(max_length=20)),
                ('F_report_path', models.TextField()),
                ('erd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcisDB.Erds')),
            ],
        ),
        migrations.CreateModel(
            name='TestReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.CharField(max_length=10)),
                ('test_log', models.TextField()),
                ('test_date', models.CharField(max_length=20)),
                ('IR_report_path', models.TextField()),
                ('fw_version', models.CharField(max_length=50)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcisDB.TestCases')),
            ],
        ),
    ]
