# Generated by Django 2.1 on 2019-03-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcisDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usb_ser', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
                ('FSN', models.CharField(max_length=20)),
                ('remove_status', models.BooleanField()),
                ('dead_date', models.CharField(blank=True, max_length=25, null=True)),
                ('subordinate_mac_addr', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SubordinateStaticInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_version', models.CharField(max_length=20)),
                ('birthday', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=40)),
                ('mac_addr', models.CharField(max_length=45)),
                ('remove_status', models.BooleanField()),
                ('dead_date', models.CharField(blank=True, max_length=25, null=True)),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='testcases',
            name='delete_status',
            field=models.NullBooleanField(),
        ),
    ]
