# Generated by Django 2.1 on 2019-03-08 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcisDB', '0002_auto_20190301_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date_on_pi', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=20)),
                ('slave_mac_addr', models.CharField(max_length=20)),
                ('FSN', models.CharField(max_length=100)),
                ('case_name', models.CharField(max_length=20)),
                ('test_result', models.CharField(max_length=20)),
                ('test_campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AcisDB.TestCampaign')),
            ],
        ),
    ]
