# Generated by Django 2.1 on 2019-02-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcisDB', '0003_auto_20190227_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutstaticinfo',
            name='remove_status',
            field=models.BooleanField(),
        ),
    ]
