# Generated by Django 2.1 on 2019-02-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcisDB', '0004_auto_20190227_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutstaticinfo',
            name='dead_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='slavestaticinfo',
            name='dead_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
